name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest test/test_train.py

  train_and_quantize:
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model and quantize
        run: |
          python src/train.py
          python src/quantize.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            regression_model.joblib
            unquant_params.joblib
            quant_params.joblib

  build_and_test_container:
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - uses: actions/checkout@v3
      - name: Download model artifacts
        uses: actions/download-artifact@v3
        with:
          name: model-artifacts
      - name: Build Docker image
        run: docker build -t mlops_assignment .
      - name: Run Docker container and verify prediction
        run: docker run mlops_assignment



